### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by GuardianTempest** [triverske/ultimatearena#59] opened 2018-06-28 13:17 UTC
1. When not playing fullscreen, the game window is permanently locked into the center of the screen and cannot be moved. Very minor but annoying that the bottom of the screen is cropped by the task bar.

2. Steam Workshop items are not showing up unless I manually transfer the folders over, it can get annoying when updating a lot of characters.

3. Even more minor, editors still aren't available in full screen. It's been a long time, shouldn't there be something?

**Comment by triverske** [comment] 2018-06-28 17:41
Thanks for the report, looking into these right now

**Comment by triverske** [comment] 2018-06-28 18:08
So regarding point 1, it's been undocumented for a long time but you can move the window by holding TAB. I've now put this information in the settings window as that's probably the easiest place for people to see it. 

Regarding point 2, this was an error and I've fixed it in 4f93310 (Steam Version v2.4.1)

Regarding point 3, the editors don't work at all screen resolutions so making them windowed mode only is a lazy workaround as most people can put up with it. If this is something that is desperately wanted by the community submit it as a feature request but as it stands it's working as intended so I'll go ahead and close this issue.

Thanks again for the report.

**Closed by triverske** 2018-06-28 18:08 UTC

**Comment by GuardianTempest** [comment] 2018-06-29 01:20
Thank you for the swift response, you're a great developer.
